repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
  
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml


  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        args:
          - -r
          - requirements.txt
          - --ignore-vuln
          - CVE-2026-45829
          - --ignore-vuln
          - CVE-2025-69872

  - repo: local
    hooks:
      - id: ruff
        name: ruff formatter
        entry: ruff format
        stages: [pre-commit]
        language: system
        types: [python]
      - id: ruff
        name: ruff linter
        entry: ruff check --fix
        stages: [pre-commit]
        language: system
        types: [python]
      - id: mypy
        name: mypy checks
        entry: mypy .
        stages: [pre-commit]
        language: system
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      - id: pyrefly
        name: pyrefly checks
        entry: pyrefly check
        stages: [pre-commit]
        language: system
        types: [python]
        pass_filenames: false
      - id: vulture
        name: vulture checks
        entry: vulture . --min-confidence 80
        stages: [pre-commit]
        language: system
        types: [python]
        pass_filenames: false
      - id: bandit
        name: bandit checks
        entry: bandit -r . --skip B101
        stages: [pre-commit]
        language: system
        types: [python]
        pass_filenames: false